SET KAFKA_HOME=.
SET KAFKA_BIN_FOLDER=%KAFKA_HOME%\bin\windows
SET KAFKA_CONFIG_FOLDER=%KAFKA_HOME%\config
SET JAVA_HOME=D:\bin\java\openjdk11
SET LOG_FOLDER=%KAFKA_HOME%\logs
SET ZOOKEEPER_FOLDER=%KAFKA_HOME%\tmp\zookeeper
SET KAFKA_LOG_FOLDER=%KAFKA_HOME%\tmp\kafka-logs